### PR TITLE
Add support for Office 2016

### PR DESCRIPTION
**Pull request by mkszuba**
Essentially the same as for 2013, just with different version numbers. Successfully tested on the German x64 Professional Plus edition.

### CODE REVIEW

**Comment by marcindulak** [comment]
Are there plans to get it merged?

**Comment by bastelfreak** [comment]
Hi @mkszuba,
Sorry for the slow response :( Are you able to rebase against our latest master branch?

**Comment by mkszuba** [comment]
Here you go. Green across the board, which is hardly surprising considering I only had to accommodate for a typo fix.

**Comment by bastelfreak** [comment]
Thanks @mkszuba !

**Pull request merged**
