### PR TITLE
Modulesync

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by bastelfreak** [comment]
this is a bit strange here. @nibalizer and I are unable to reproduce the rubocop errors on our local systems. Does anybody here have an idea? 

CC: @rnelson0 @jyaworski

**Comment by bastelfreak** [comment]
(also I played with Style/IndentHash and Style/AlignHash and they were reverting each other several times :( )

**Comment by rnelson0** [comment]
I was able to replicate the rubocop errors, `git clone https...; git checkout modulesync; export (stuff from .travis.yml), bundle install --without system_tests development, bundle exec rake $CHECK`, gives `8 files inspected, 162 offenses detected`. Silly question time: did you remember to check out the modulesync branch?

**Comment by bastelfreak** [comment]
I'm on the correct branch, Ruby/bundler versions match travis, just my gem binary is a little bit older:
```
bastelfreak@bastelfreak-ws ~/modulesync_config/modules/puppet-msoffice $ git status
On branch modulesync
Your branch is up-to-date with 'origin/modulesync'.
nothing to commit, working directory clean
bastelfreak@bastelfreak-ws ~/modulesync_config/modules/puppet-msoffice $ git remote -v
origin	git@github.com:voxpupuli/puppet-msoffice.git (fetch)
origin	git@github.com:voxpupuli/puppet-msoffice.git (push)
bastelfreak@bastelfreak-ws ~/modulesync_config/modules/puppet-msoffice $ git pull
Already up-to-date.
bastelfreak@bastelfreak-ws ~/modulesync_config/modules/puppet-msoffice $ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
bastelfreak@bastelfreak-ws ~/modulesync_config/modules/puppet-msoffice $ bundle --version
Bundler version 1.12.3
bastelfreak@bastelfreak-ws ~/modulesync_config/modules/puppet-msoffice $ gem --version
2.5.1
bastelfreak@bastelfreak-ws ~/modulesync_config/modules/puppet-msoffice $ export STRICT_VARIABLES="yes"
bastelfreak@bastelfreak-ws ~/modulesync_config/modules/puppet-msoffice $ export PUPPET_VERSION='4.4'
bastelfreak@bastelfreak-ws ~/modulesync_config/modules/puppet-msoffice $ bundle exec rake rubocop
You have requested:
  puppet = 4.4

The bundle currently has puppet locked at 4.4.2.
Try running `bundle update puppet`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
Run `bundle install` to install missing gems.
bastelfreak@bastelfreak-ws ~/modulesync_config/modules/puppet-msoffice $ export PUPPET_VERSION='~> 4.0'
bastelfreak@bastelfreak-ws ~/modulesync_config/modules/puppet-msoffice $ bundle update
Fetching https://github.com/voxpupuli/puppet-blacksmith.git
Fetching https://github.com/voxpupuli/voxpupuli-release-gem.git
Fetching https://github.com/puppetlabs/puppetlabs-strings.git
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies.......
Using rake 11.1.2
Using CFPropertyList 2.2.8
Using ast 2.2.0
Using diff-lcs 1.2.5
Using unf_ext 0.0.7.2
Using facter 2.4.6
Using json 1.8.3
Using json_pure 1.8.3
Using stomp 1.3.5
Using systemu 2.6.5
Using metaclass 0.0.4
Using spdx-licenses 1.1.0
Using mime-types 2.99.1
Using netrc 0.11.0
Using powerpack 0.1.1
Using puppet-lint 1.1.0 from https://github.com/rodjek/puppet-lint.git (at master@eec92c1)
Using yard 0.8.7.6
Using rspec-support 3.4.1
Using rainbow 2.1.0
Using rspec-puppet-utils 2.2.1
Using ruby-progressbar 1.8.1
Using unicode-display_width 1.0.5
Using bundler 1.12.3
Using puppet-syntax 2.1.0
Using parser 2.3.1.0
Using unf 0.1.4
Using jgrep 1.4.0
Using hiera 3.1.2
Using mcollective-client 2.8.4
Using mocha 1.1.0
Using metadata-json-lint 0.0.11
Using puppet-lint-absolute_classname-check 0.1.3
Using puppet-lint-classes_and_types_beginning_with_digits-check 0.1.0
Using puppet-lint-leading_zero-check 0.1.0
Using puppet-lint-trailing_comma-check 0.3.1
Using puppet-lint-unquoted_string-check 0.2.5
Using puppet-lint-variable_contains_upcase 1.0.0
Using puppet-lint-version_comparison-check 0.1.2
Using rspec-core 3.4.4
Using rspec-expectations 3.4.0
Using rspec-mocks 3.4.1
Using rubocop 0.39.0
Using domain_name 0.5.20160310
Using facterdb 0.3.5
Using puppet 4.4.2
Using rspec 3.4.0
Using rubocop-rspec 1.4.1
Using http-cookie 1.0.2
Using puppet-strings 0.4.0 from https://github.com/puppetlabs/puppetlabs-strings.git (at master@8c232fb)
Using rspec-puppet-facts 1.5.0
Using rspec-puppet 2.4.0 from https://github.com/rodjek/rspec-puppet.git (at master@79d5373)
Using rest-client 1.8.0
Using puppetlabs_spec_helper 1.1.1
Using puppet-blacksmith 3.3.1 from https://github.com/voxpupuli/puppet-blacksmith.git (at master@4029c26)
Using voxpupuli-release 0.3.0 from https://github.com/voxpupuli/voxpupuli-release-gem.git (at master@0624378)
Bundle updated!
Gems in the groups system_tests and development were not installed.
bastelfreak@bastelfreak-ws ~/modulesync_config/modules/puppet-msoffice $ bundle exec rake rubocop
/home/bastelfreak/modulesync_config/modules/puppet-msoffice/.vendor/ruby/2.3.0/gems/yard-0.8.7.6/lib/yard/code_objects/base.rb:50: warning: already initialized constant YARD::CodeObjects::CONSTANTMATCH
/home/bastelfreak/modulesync_config/modules/puppet-msoffice/.vendor/ruby/2.3.0/bundler/gems/puppetlabs-strings-8c232fba7ed7/lib/puppet_x/puppetlabs/strings/yard/core_ext/yard.rb:10: warning: previous definition of CONSTANTMATCH was here
Running RuboCop...
Inspecting 0 files


0 files inspected, no offenses detected
```

This seems to be an issue with the rake task, calling rubocop directly works:

```
bundle exec rubocop -c .rubocop.yml
.....
8 files inspected, 162 offenses detected
```

**Comment by rnelson0** [comment]
Try a git clean --ffdx then do a bundle install again?

-- 

Rob Nelson
rnelson0@gmail.com

**Comment by bastelfreak** [comment]
Tried that, the rubocop rake task still finds no issues. Anyways I almost fixed most of them by hand, it should be ready for merge shortly.

**Comment by bastelfreak** [comment]
Green \o/

**Pull request merged**
